apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
    app: zookeeper
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: server
    - port: 3888
      name: leader-election     
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
    app: zookeeper
