apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: node-exporter
  labels:
    app: node-exporter
spec:
  ports:
  - name: node-exporter
    port: 9100
    targetPort: 9100
  selector:
    app: node-exporter
