apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: logging
  name: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Gi
