# yamllint disable rule:line-length
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 3 
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  serviceName: zookeeper
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - zookeeper
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: zookeeper
          image: caronwills/zookeeper-rhel-3.8.0-v2:latest
          command:
            - /bin/sh
            - -c
            - export ZOO_MY_ID=$(expr $(hostname | grep -o "[[:digit:]]*$") + 1) && /docker-entrypoint.sh zkServer.sh start-foreground            
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          env:
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: rouk
            - name: ZOO_SERVERS
              value: "server.1=zookeeper-0.zookeeper:2888:3888;2181 \
                      server.2=zookeeper-1.zookeeper:2888:3888;2181 \
                      server.3=zookeeper-2.zookeeper:2888:3888;2181"    
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: data
            - name: data
              mountPath: /datalog
              subPath: datalog
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi


