apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: LoadBalancer
  selector:
    app: kafka
  ports:
    - port: 9094
      name: kafka-2
    - port: 9092
      name: kafka-0  
    - port: 9093
      name: kafka-3  
