apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    app: kafka
spec:
  type: {{ .Values.service.type }}
  selector:
    app: kafka
  ports:
    - port: 9094
      name: kafka-2
    - port: 9092
      name: kafka-0
    - port: 9093
      name: kafka-3
