apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd # <-- APACHE IMAGE  
        # LIFECYCLE DEFINITION START 
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo $HOSTNAME > htdocs/hostname.html"]
        # LIFECYCLE DEFINITION END
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/apache2
            name: http-conf
      volumes:
        - name: http-conf
          configMap:
            name: http-conf
            items:
              - key: httpd.conf
                path: httpd.conf