apiVersion: v1
kind: ConfigMap
metadata:
  name: http-conf
data:
  httpd.conf: |
    # httpd.conf content
    ########################################################
    # httpd 2.4.10 or plus is needed to work with headers %
    Listen 8056
    # Enable ldap module if used
    # yum -y install mod_ldap
    # Disable ldaps trust if used
    LDAPVerifyServerCert off

    <VirtualHost *:8056>
      ServerAdmin sysadmin@home.labs
      DocumentRoot "/var/lib/www"

      ErrorLog "logs/kibana-error.log"
      CustomLog "logs/kibana-access.log" commonvhost

      ProxyPreserveHost On
      ProxyRequests On

      # Basic auth with LDAP(s)
      <Proxy *>
        Order deny,allow
        Allow from all
        Authtype Basic
        Authname "Password Required"
        AuthBasicProvider ldap
        LDAPReferrals Off
        AuthLDAPBindAuthoritative Off
        AuthLDAPRemoteUserAttribute uid
        # check users credentials from ldaps
        AuthLDAPURL "ldaps://192.168.56.1:636/ou=users,dc=home,dc=labs?uid"
        AuthLDAPBindDN uid=bindinguser,ou=system
        # Make sure to put the bindinguser password below without the "" 
        AuthLDAPBindPassword ***********
        Require valid-user
        # Get the authenticated userid
        Define ES_USERNAME %{REMOTE_USER}
        # This is the unique password to use for all users that going to be created inside of Elatic stack
        Define ES_PASSWORD "*****************"
        Define CREDENTIALS ${ES_USERNAME}:${ES_PASSWORD}
        # Send the Authorization header to Kibana
        RequestHeader set Authorization "expr=Basic %{base64:${CREDENTIALS}}"
      </Proxy>

      # Kibana URL
      ProxyPass / http://192.168.56.1:5601/
      ProxyPassReverse / http://192.168.56.1:5601/

    </VirtualHost>   
