---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-budget
spec:
  selector:
    matchLabels:
      app: zk
  minAvailable: 1
---  
apiVersion: v1
kind: Service
metadata:
  name: zk
  labels:
    app: zk
spec:
  clusterIP: None
  selector:
    app: zk
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
