apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: spy
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: spy
      image: eu.gcr.io/loodse-training-playground/loodse-training/curl:0.0.1
      command: [ "sleep", "1h" ]
