{{- if hasKey . "config" }}
{{ toYaml .config }}
{{- else }}

{{- $global := . }}
{{- $base := dict "config" .Values.config }}
{{- $items := prepend .Values.extraInstances $base }}
{{- range $idx, $item := $items }}
{{- $config := mergeOverwrite $item.config $global.Values.common.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus-smartctl-exporter.fullname" $global }}-{{ $idx }}
  labels:
    {{- include "prometheus-smartctl-exporter.labels" $global | nindent 4 }}
    idx: i{{ $idx }}
data:
  smartctl_exporter.yaml: |
    smartctl_exporter:
{{ toYaml $config | indent 6 }}
{{- end }}
{{- end }}
