apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      containers:
        - name: busybox
          image: busybox:1.32.0
          command: ["sleep"]
          args: ["10"]
      restartPolicy: Never
