apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 3
  serviceName: kafka
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: caronwills/kafka-rhel-v1:latest 
          ports:
            - containerPort: 9094
          env:
            - name: HOSTNAME_COMMAND
              value: "echo \"$HOSTNAME.kafka.hornet.svc.cluster.local\""
            - name: BROKER_ID_COMMAND
              value:  "hostname | awk -F'-' '{print $2}'"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-0.zookeeper.hornet.svc.cluster.local:2181,\
                      zookeeper-1.zookeeper.hornet.svc.cluster.local:2181,\
                      zookeeper-2.zookeeper.hornet.svc.cluster.local:2181"
            - name: KAFKA_LISTENERS
              value: "INSIDE://:9092,OUTSIDE://:9094"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INSIDE"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_LOG_DIRS
              value: "/kafka-logs"
            - name: JMX_PORT
              value: "9999"
          volumeMounts:
            - name: logs
              mountPath: /kafka-logs
              subPath: logs
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
  volumeClaimTemplates:
    - metadata:
        name: logs
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
