{{- if and ( .Values.cloudsqlproxy.enabled ) ( not .Values.cloudsqlproxy.credentialsSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "prometheus-mysql-exporter.cloudsqlsecret" . }}
  labels:
    {{- include "prometheus-mysql-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.cloudsqlproxy.credentials | b64enc }}
{{- end }}
