apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  - name: telemetry
    port: 8081
    targetPort: 8081
  selector:
    app: kube-state-metrics
